name: CI

on: 
  push:

jobs:
  build:
    name: Run the README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup stack
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8'
          enable-stack: true
          stack-version: 'latest'

      - run: ./go
